### ISSUE TITLE
How to use the routes drawing factory

### ISSUE THREAD

**Issue by thegodone** [MolecularAI/reaction_utils#19]
Can you add few cases to render a route like ?

```
from rxnutils.routes.readers import reactions2route
from rxnutils.routes.image import RouteImageFactory

import json

route = reactions2route(
        ["Cl.C1=CC=CC=C1>>ClC1=CC=CC=C1", "CO.ClC1=CC=CC=C1>>COC1=CC=CC=C1"]
    )
route.reaction_tree

RouteImageFactory(route.reaction_tree)
img = RouteImageFactory(route.reaction_tree);
img.image

```

**Comment by SGenheden** [comment]
Hello Guillaume,

If you have the route-object from `reactions2route` then you can just call `route.image()` to produce the image. Behind the scene it  does basically the final three lines of your example. 

What else are you looking for?

**Comment by thegodone** [comment]
Hello Samuel,

Yes the route.image() works in this case but if I work from a pandas dataframe, it failed.  
```
df = pd.DataFrame(
    {
        "smiles": [
            "Cl.C1=CC=CC=C1>>ClC1=CC=CC=C1",
            "CO.ClC1=CC=CC=C1>>COC1=CC=CC=C1",
        ],
        "foo": ["bar", None],
        "id": [0, 0],
    }
)
routes = read_reactions_dataframe(df, "smiles", ["id"], ["foo"])
routes.image()

my error is: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/var/folders/4w/xmf8nmhs51j4vjsttzcxmmm00000gn/T/ipykernel_67151/2377239218.py](http://localhost:8889/var/folders/4w/xmf8nmhs51j4vjsttzcxmmm00000gn/T/ipykernel_67151/2377239218.py) in <cell line: 0>()
     10 )
     11 routes = read_reactions_dataframe(df, "smiles", ["id"], ["foo"])
---> 12 routes.image()

[~/miniforge3/envs/mlxgraphenv-py311/lib/python3.11/site-packages/pandas/core/generic.py](http://localhost:8889/lab/tree/~/miniforge3/envs/mlxgraphenv-py311/lib/python3.11/site-packages/pandas/core/generic.py) in __getattr__(self, name)
   6297         ):
   6298             return self[name]
-> 6299         return object.__getattribute__(self, name)
   6300 
   6301     @final

AttributeError: 'Series' object has no attribute 'image'

```

PS: I was able to install your package with python 3.11 and manually clean up few deps in the poetry.lock files to install on arm64 mac. Only issue was that it installs numpy 2.0.1.

**Comment by thegodone** [comment]
Another question, Can we add text in the image ?

**Comment by SGenheden** [comment]
Glad you figured it out. The `read_reactions_dataframe` routine returns a Pandas series with the routes. So yes you need to do indexing into that series.

The object that is returned by the `image()` method is a PIL image, so yes you can manipulate it however you like.  You can wrap the image in a PIL `ImageDraw` object and then do the manipulations you want. However, this is not conveniently support by the current code.

**Comment by thegodone** [comment]
Great thanks for the details. Where is the piece of code to render the reactions route ?


- This code works only if img is shown in a jupyter lab cell previously otherwise it failed ... anyway:
```

from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype("Arial.ttf", 12)

d = ImageDraw.Draw(img)

d.multiline_text((10, 10), "Hello\nWorld", font=font, fill=(0, 0, 0))
img.show()

```

**Comment by SGenheden** [comment]
Yes. All the code to generate the route images are in `image.py`. This was actually lifted from `aizynthfinder`, when we added routes to `rxnutils`. The code uses some RDKit and PIL routines, but that should be the only dependencies.

**Comment by thegodone** [comment]
I was able to add a text: 
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/9c2f881d-db3e-4546-a1cf-9f5e32cb25c4">
