### ISSUE TITLE
Upload package to pypi

### ISSUE THREAD

**Issue by marcosfelt** [MolecularAI/reaction_utils#2]
It's not best practice, to require people to use poetry to install the package (and trust me I love poetry!). Would it be possible to upload to pypi? Poetry has a nice command for doing this: https://python-poetry.org/docs/libraries/#publishing-to-pypi

**Comment by SGenheden** [comment]
We are looking into using RDkit with pypi which would enable pypi package. But we have some issues.

You can though install the rxnutils with pip using `pip install https://github.com/MolecularAI/reaction_utils/archive/refs/tags/v1.0.0.tar.gz`

**Comment by marcosfelt** [comment]
What if you make `rdkit_pypi` an optional dependency (see [here](https://python-poetry.org/docs/pyproject/#extras) for how to do this with poetry)? Then you can give people the following options
1. `pip install rxn_utils[rdkit]` which installs rdkit via pypi
2. Install rdkit on their own (e.g., using conda) then do `pip install rxn_utils`

**Comment by SGenheden** [comment]
We have decided to move the a pure pip-installable package. Update is coming soon.

**Comment by SGenheden** [comment]
It is now available on pypi: https://pypi.org/project/reaction-utils

**Comment by marcosfelt** [comment]
Works! Thanks :)
